[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'command_prompt'
version = '1.0.0'
description = 'Command prompt example.'
requires-python = '>=3.7'

[tool.setuptools.packages.find]
where = ['src']
